### ISSUE TITLE
Local IP adress

### ISSUE THREAD

**Issue by mrmate2** [asmaklad/TeleView#14]
Good day! Again, many thanks for such great project.
2 questions: Is it possible to make such function in telegram bot interface:to show present IP adressof Teleview in LAN network?
Every time i have home electricity restart-my router assign new ip adrees to esp32cam, and webinterface access ip adress is changing.
The best is to be something like this:
"I am alive,LAN IP xxx.xxx.x.xx".
Is it possible to implement it?
And second question: Last year You mentioned about working on Servo control function...
Any success?

**Comment by asmaklad** [comment]
Hi mrmate2
You can see the local ip from /options
If you upload the latest version in master branch.
Unfortunately i didnt complete the servo thingy. I will try later to work on this.

**Comment by mrmate2** [comment]
Many thanks for reply.
IP adress question is closed.
Will ill hope and wait for servo control. Thanks!
