### ISSUE TITLE
Print text on screen

### ISSUE THREAD

**Issue by Lolo130207** [asmaklad/TeleView#15]
Hello I use your code and everything is ok.
I use TTGO Camera and when I push the PIN=34 button its take a picture.

Now I just want to print My name no line 1 and a word like "let's ring" on line 3.

Is it possible to tell me how to do or to add this feature directly in the web page.

Regards.

**Comment by Lolo130207** [comment]
Ok thanks so I put it in the display.h ?

**Comment by asmaklad** [comment]
no you put it in the TeleView.ino loop , but use the functions that are in the "display.h"
