### ISSUE TITLE
CV motion detect delay

### ISSUE THREAD

**Issue by mrmate2** [asmaklad/TeleView#16]
Good day.
I am having rather long delays while receiving CV motion detect notifications/photo.
Sometimes up to 2-3minutes.Resolution of photo is set to QVGA, but anyway no improvement. Very frequently no reaction to motion in front of camera at all.Seems this function works very unstable, at least in my case.
Detects only rather big movements of very big objects.Is there a way to adjust sensitivity and to speed up motion detect notification? Thanks

**Comment by asmaklad** [comment]
Thank you memate2 for your feedback.
I agree with you that the CV motion detection feature is not full ready yet. I might have jumped the gun by adding it. 
I have tried to use some other code to integrate that feature but it doesn't work as intended. The algorithm in general needs refinement for detection changed pixels per each light condition. but as I mentioned I imported the code from another GIT project.
Unfortunately I don't have the time now to fix this. but I will keep it mind.
Best Regards
asmaklad

**Comment by asmaklad** [comment]
P.S.:  You find reference to the other git project in ElequentVision.h .

// suorces
// https://github.com/eloquentarduino/EloquentArduino/blob/1.1.8/examples/ESP32CameraNaiveMotionDetection/ESP32CameraNaiveMotionDetection.ino
// https://eloquentarduino.github.io/2020/05/easier-faster-pure-video-esp32-cam-motion-detection/?utm_source=old_version
