### ISSUE TITLE
Quality of the motion detection snapshots is not great

### ISSUE THREAD

**Issue by nguterresn** [asmaklad/TeleView#18]
Hey there!

I've been trying to use this recently and got really greats results apart from the video motion detection.

Here is an example of the quality of the snapshots:

![Captura de ecrã 2023-11-28, às 23 05 18](https://github.com/asmaklad/TeleView/assets/38976366/a185b696-710c-4ce3-8198-9f157764dc2f)

It works well if it is just a capture or streaming (in general), but not for telegram.

My board is the `CAMERA_MODEL_AI_THINKER`  by the way.

**Comment by asmaklad** [comment]
It is always a pleasure when I hear someone is using the Teleview project. 
I will be glad to support you.
Unfortunately, the Computer vision motion detection is still not complete yet, also capturing video is still something I need to work on. 
However for your specific issue, Could it be the Power supply or cable your are using ? 
for the ESP32-CAM it is rather a known issue about power for the Wifi and Camera at the same time.
1) Try changing the cable and power supply and tell me.
2) Try reducing the resolution.

Please tell me how it goes.

**Comment by nguterresn** [comment]
> It is always a pleasure when I hear someone is using the Teleview project.
> I will be glad to support you.

Well, thank you! This project is fantastic! 

> However for your specific issue, Could it be the Power supply or cable your are using ?

Oh! I'm using a USB power cable connected through a USB dongle which is then connected by USB-C to the Mac. I suppose the ESP32 Cam can draw more than 500mA sometimes? I'll try this once I get back home.

**Comment by nguterresn** [comment]
https://github.com/asmaklad/TeleView/assets/38976366/3efade85-4a37-4a60-94cd-15bfe3280c9d

I'm now using a great power supply to power the ESP32 Cam. Above is an example of how the stream works. Even with low res 320x240, it breaks often every 2 seconds.

**Comment by asmaklad** [comment]
ok ,now I understand that the glitching image is not happening anymore and this is a new issue you are having ? right ?

If so: commenting on this, I assume this interruption you are having is the polling mechanism for Telegram. 
Every now and then the Teleview has to contact Telegram and check if there are commands lined up for the bot. You will see even more interruption if you actually ask the bot to sendPhoto while doing streaming.
I actually had to program it in a special way to be able to stream and respond to SendPhoto from telegram bot at the same time. In earlier version it was that as long as there is streaming going on, no Telegram pulling is taking place.

If you really want less interruption then what we could do is:
1) increase WIFI/Signal/internet speed somehow.
2) Disable Debugging if already enabled (from the Arduino IDE, I think the menu item looks like this : https://iotespresso.com/core-debug-level-in-esp32/ ).
3) Reduce the pulling cycles of the BOT ( I will check for a procedure to do that).

But before I do any code changes, I need to understand a bit about the scenario you are using the device for. When do you use streaming and when do you use the telegram messaging ?

Regards

**Comment by nguterresn** [comment]
No, I'm sorry If I expressed my self wrongly. The first issue still exists. Then, I noticed the second one. 

They could be or not related, so I wrote about it.

> When do you use streaming and when do you use the telegram messaging ?

I'd like to only use the telegram bot to take some snapshots whenever I want. Would be nice to have the motion detection working, but that's a plus for me. :)

**Comment by asmaklad** [comment]
ok I see.
So you upgraded the power supply, and you still see the same issue of distorted image ?

It seems to me that this glitchy image is occurring occasionally. right ? or is it with every telegram picture sent ? 
it seems also from your statement, it is only when working with telegram. Streaming and other sketches are not causing the same problems. 

All my thoughts are really going to the direction of the Network traffic and packet exchange fluency with Telegram.

This kind of distorted image, is when few bytes are somehow missing or distorted upon capture or sending to Telegram. 

Please try the following
* Reduce the resolution (to reduce the file size uploaded to telegram).
* Enhance the WIFI/Signal/internet speed somehow.. (move closer to the router,reduce walls , open metal curtains or shades between the ESP and the Router, ...etc). 
* If you have the camera connected to the computer, do you see any messages or logs displayed at the serial monitor tool ? this could reveal if there is already excessive debug messages being serialized at the same time the network traffic is going on.


regards

**Comment by nguterresn** [comment]
> So you upgraded the power supply, and you still see the same issue of distorted image ?

Just to be clear, I was using a USB Shield for the ESP CAM connected to my Mac USB Dongle. Therefore, the power could be somehow limited. I keep the USB shield, but now I'm supplying the ESP32 with a proper USB A power supply. The cable might still be an issue and the USB shield might still be an issue (maybe due to LDO current).

> Reduce the resolution (to reduce the file size uploaded to telegram).

I've tried this but the issue remained.

> Enhance the WIFI/Signal/internet speed somehow.. (move closer to the router,reduce walls , open metal curtains or shades between the ESP and the Router, ...etc).

The ESP32 is quite close to the Router, around ~1m and I'm the only connection to it.

> If you have the camera connected to the computer, do you see any messages or logs displayed at the serial monitor tool ? this could reveal if there is already excessive debug messages being serialized at the same time the network traffic is going on.

I'll try this soon! Thanks :)
