### ISSUE TITLE
Problems with Compiling

### ISSUE THREAD

**Issue by SyncroMischi** [asmaklad/TeleView#19]
Hy,
i have problems with compiling your program. I get this error and don't understand why:

/home/builder/Arduino/libraries/arduinojson_7_2_0/src/ArduinoJson/compatibility.hpp:89:23: error: 'struct SpiRamAllocatorST' has no member named 'reallocate'; did you mean 'deallocate'?
     return _allocator.reallocate(ptr, new_size);
            ~~~~~~~~~~~^~~~~~~~~~
            deallocate

is it possible that you can help me

Thanks
 SyncroMischi

**Comment by asmaklad** [comment]
Thank you for trying to use this project, I am glad that it is helping people.
According to this:
https://github.com/asmaklad/TeleView?tab=readme-ov-file#required-libraries

You need to downgrade your arduinojson library from 7.2.0 to 6.19.4

**Comment by SyncroMischi** [comment]
Oh your a genius! That solved the problem! Now I can Compile the Sketch!
I will put the Camera in my new Elegoo Mars 2 Pro SLA 3D Printer so I can see if it is finished and to monitor the print status.
This is a very cool Project and I wish I can someday program something like this by my own.

Congrats
SyncroMischi

**Comment by asmaklad** [comment]
That is good to hear. 
You know you could have more than one person controlling the Teleview by adding the chat_id of a Telegram group?
https://github.com/asmaklad/TeleView?tab=readme-ov-file#having-more-than-one-user-to-use-the-bot
