### ISSUE TITLE
Error: multiple libraries were found for wifi.h esp32

### ISSUE THREAD

**Issue by prakash52kar** [asmaklad/TeleView#3]
Sir,

I am exited to use this code but getting error "multiple libraries were found for wifi.h esp32" and also "Multiple libraries were found for "SD.h"" while compiling the code

**Comment by anmorfe** [comment]
Hello:

I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
C:\Program Files (x86)\Arduino\libraries.

This worked for me.

**Comment by prakash52kar** [comment]
> Hello:
> 
> I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
> C:\Program Files (x86)\Arduino\libraries.
> 
> This worked for me.
> 
> I will be grateful if you comment if the program works in your board... I have the ESP32-cam, and I have had no luck.... I have been able to load the code to the board but it seems there are some kind of problem about comunication between board and telegram bot...

Hi Dear, 
Thank you for your comment. I will try in the evening.
However in your issue you told that you have tried "https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino" Earlier I also had problem of connecting with telegram.  I do also tried and I was able to connect to telegram. What you have to do that just write   "client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;" let me know...

**Comment by anmorfe** [comment]
> > Hello:
> > I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
> > C:\Program Files (x86)\Arduino\libraries.
> > This worked for me.
> > I will be grateful if you comment if the program works in your board... I have the ESP32-cam, and I have had no luck.... I have been able to load the code to the board but it seems there are some kind of problem about comunication between board and telegram bot...
> 
> Hi Dear,
> Thank you for your comment. I will try in the evening.
> However in your issue you told that you have tried "https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino" Earlier I also had problem of connecting with telegram. I do also tried and I was able to connect to telegram. What you have to do that just write "client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;" let me know...

Great... It works with this little change ("client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;"), but I dont' understand whi this one: https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_Telegram_getUpdates/ESP32-CAM_Telegram_getUpdates.ino doesn't work with the same change... It gets the next error. "client_tcp does not name a type"

**Comment by prakash52kar** [comment]
> > > Hello:
> > > I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
> > > C:\Program Files (x86)\Arduino\libraries.
> > > This worked for me.
> > > I will be grateful if you comment if the program works in your board... I have the ESP32-cam, and I have had no luck.... I have been able to load the code to the board but it seems there are some kind of problem about comunication between board and telegram bot...
> > 
> > 
> > Hi Dear,
> > Thank you for your comment. I will try in the evening.
> > However in your issue you told that you have tried "https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino" Earlier I also had problem of connecting with telegram. I do also tried and I was able to connect to telegram. What you have to do that just write "client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;" let me know...
> 
> Great... It works with this little change ("client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;"), but I dont' understand whi this one: https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_Telegram_getUpdates/ESP32-CAM_Telegram_getUpdates.ino doesn't work with the same change... It gets the next error. "client_tcp does not name a type"

Hi,

I am happy to know it. I don't much but It is given in the troubleshooting of TelegramBotLibrary.

**Comment by prakash52kar** [comment]
> > > > Hello:
> > > > I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
> > > > C:\Program Files (x86)\Arduino\libraries.
> > > > This worked for me.
> > > > I will be grateful if you comment if the program works in your board... I have the ESP32-cam, and I have had no luck.... I have been able to load the code to the board but it seems there are some kind of problem about comunication between board and telegram bot...
> > > 
> > > 
> > > Hi Dear,
> > > Thank you for your comment. I will try in the evening.
> > > However in your issue you told that you have tried "https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino" Earlier I also had problem of connecting with telegram. I do also tried and I was able to connect to telegram. What you have to do that just write "client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;" let me know...
> > 
> > 
> > Great... It works with this little change ("client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;"), but I dont' understand whi this one: https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_Telegram_getUpdates/ESP32-CAM_Telegram_getUpdates.ino doesn't work with the same change... It gets the next error. "client_tcp does not name a type"
> 
> Hi,
> 
> I am happy to know it. I don't know much but It is given in the troubleshooting of TelegramBotLibrary.

This might be resulting from the code in function "sendMessage2Telegram" add again in this code...!!!

**Comment by asmaklad** [comment]
Thanks  anmorfe  and  prakash52kar  for using this project I appreciate the collaborative atmosphere I sense in your messages. 
I hope both your issues are resolved now . 
right ?

**Comment by asmaklad** [comment]
As for PIR support , the Teleview supports using PIR  and OLED display. 
it is automaticly enabled when you define :
#define CAMERA_MODEL_TTGO_T1_CAMERA
or you can hack camera_pins.h  for yoir own solution by imitating the definitions, for example:
#define SDA_PIN 21
#define SCL_PIN 22
#define I2C_DISPLAY_ADDR  0x3c
#define USE_OLED_AS_FLASH 1 // the OLED is on the same side as the camera
//#define I2C_BME280_ADDR   0x3d
#define PIR_PIN           33 //GPIO_INPUT_IO_33 //AS312
#define BUTTON_PIN        34

**Comment by anmorfe** [comment]
> Thanks anmorfe and prakash52kar for using this project I appreciate the collaborative atmosphere I sense in your messages.
> I hope both your issues are resolved now .
> right ?

Absolutely not.... I couln't make your code works...  We were speaking about another project. I would be grateful if you would try your code and verify if there is some kind of problem...
Thanks in advance.

**Comment by asmaklad** [comment]
hi 
please check this solution and try it out:
https://github.com/asmaklad/TeleView/issues/2#issuecomment-824474249

**Comment by prakash52kar** [comment]
> Hello:
> 
> I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
> C:\Program Files (x86)\Arduino\libraries.
> 
> This worked for me.
> 
> I will be grateful if you comment if the program works in your board... I have the ESP32-cam, and I have had no luck.... I have been able to load the code to the board but it seems there are some kind of problem about comunication between board and telegram bot...

HI,
I do not have this folder at this location but "C:\Users\€Home\OneDrive\Documents\Arduino\libraries" there I do not see these files folders..

**Comment by prakash52kar** [comment]
> > > > > Hello:
> > > > > I have had the same problem, the solution is to move both of folders, (Wifi and sd) from the next adrress:
> > > > > C:\Program Files (x86)\Arduino\libraries.
> > > > > This worked for me.
> > > > > I will be grateful if you comment if the program works in your board... I have the ESP32-cam, and I have had no luck.... I have been able to load the code to the board but it seems there are some kind of problem about comunication between board and telegram bot...
> > > > 
> > > > 
> > > > Hi Dear,
> > > > Thank you for your comment. I will try in the evening.
> > > > However in your issue you told that you have tried "https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_PIR_Telegram/ESP32-CAM_PIR_Telegram.ino" Earlier I also had problem of connecting with telegram. I do also tried and I was able to connect to telegram. What you have to do that just write "client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;" let me know...
> > > 
> > > 
> > > Great... It works with this little change ("client_tcp.setInsecure();" after "WiFiClientSecure client_tcp;"), but I dont' understand whi this one: https://github.com/fustyles/Arduino/blob/master/ESP32-CAM_Telegram_getUpdates/ESP32-CAM_Telegram_getUpdates.ino doesn't work with the same change... It gets the next error. "client_tcp does not name a type"
> > 
> > 
> > Hi,
> > I am happy to know it. I don't know much but It is given in the troubleshooting of TelegramBotLibrary.
> 
> The code you are trying was working for me after the changes I suggested. It was working when I was interacting the ESPCAM via bot. But when I added bot to the telegram group, the text like /capture was giving the photo but not by clicking the InlineKeybaord. It was writing as if I am replying to bot and ESPCAM was not responding. Secondly in this code there is no PIR trigger, so I stucked with that. The user of this code has given his facebook account and I sent him friend request. When he accepted it, I told him this issue. He promised that he will improve it within a week, but I am still waiting.. :-)

He (Chungi Fu) talked me on fakebook and asked for my code. Lets see he helps..

**Comment by asmaklad** [comment]
hi @prakash52kar  this is an issue with the ArduinoIDE setup on your machine. 
You can see which two folders are conflicting in the full error message .
You can send me the full error and I can tell you which folders to move. Also some information about the version of the ArduinoIDE and the Version of the installed ESP32 Board library.

**Comment by prakash52kar** [comment]
> ill waiting.. :-)

Hi, He (Chungi Fu) is very kind and spent around two hours to guide me. I am happy to inform you that he helped me and I am now getting pictures in family group by typing /capture as well as by PIR trigger...

**Comment by anmorfe** [comment]
Marvellous.... Would you share the code with me? I would like to try it...My email is antonuria@yahoo.es. Thanks in advance

**Comment by prakash52kar** [comment]
> Marvellous.... Would you share the code with me? I would like to try it...My email is [antonuria@yahoo.es](mailto:antonuria@yahoo.es). Thanks in advance

Hi, after discussion and solving the issues, he has updated the same code. Please have it. by the way I will note your email id and mine is prakash52kar@gmail.com.

**Comment by anmorfe** [comment]
I can't find it. Could you share the link, please?

**Comment by anmorfe** [comment]
Thanks, I will try it...

**Comment by prakash52kar** [comment]
> Thanks, I will try it...

Have you received my email?

**Comment by anmorfe** [comment]
Yes.....Thanks for the information.

**Comment by asmaklad** [comment]
Not enough input .
